[package]
name = "pcap-file"
edition = "2018"
version = "1.0.0-rc1"
authors = ["Courvoif <courvoif@pm.me>"]
description = "Read and write Pcap file"

license = "MIT"
documentation = "https://docs.rs/pcap-file/"
repository = "https://github.com/courvoif/pcap-file"
readme = "README.md"
keywords = ["pcap", "file", "read", "write"]
categories = ["encoding", "parsing"]

[dependencies]
byteorder = "1.3.2"
derive-into-owned = "0.1.0"
failure = "0.1.5"

[dev-dependencies]
glob = "0.3.0"