[package]
name = "pcap-file"
edition = "2018"
version = "0.10.0"
authors = ["Courvoif <courvoif@protonmail.com>"]
description = "Read and write Pcap file"

license = "MIT"
documentation = "https://docs.rs/pcap-file/"
repository = "https://github.com/courvoif/pcap-file"
readme = "README.md"
keywords = ["pcap", "file", "read", "write"]
categories = ["encoding", "parsing"]

[dependencies]
byteorder = "1.0"
failure = "0.1"
