[package]
name = "pcap-file"
edition = "2018"
version = "1.0.0-rc1"
authors = ["Courvoif <courvoif@pm.me>"]
description = "A crate to read and write Pcap and read PcapNg"

license = "MIT"
documentation = "https://docs.rs/pcap-file/"
repository = "https://github.com/courvoif/pcap-file"
readme = "README.md"
keywords = ["pcap", "pcapng", "pcap-ng", "file", "parse", "read", "write"]
categories = ["encoding", "parsing"]

[dependencies]
byteorder = "1.3.2"
thiserror = "1.0"

[dev-dependencies]
glob = "0.3.0"